spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: StockService
        uri: lb://StockService
        predicates:
        - Path=/stock/**
      - id: ProductService
        uri: lb://ProductService
        predicates:
        - Path=/product/**
            
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  file:
    name: C:/springcloudtraining/temp/apiGateway.log
  level:
    root: debug


