server:
  port: 8902

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ProductService

logging:
  file:
    name: C:/springcloudtraining/temp/product-elk.log