server:
  port: 8761 
 
eureka:
  client:
    registerWithEureka: false   #telling the server not to register himself in the service registry
    fetchRegistry: false
    
logging:
  file:
    name: C:/springcloudtraining/temp/eureka.log
  level:
    root: debug
    