server:
  port: 8900

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: StockService

logging:
  file:
    name: C:/springcloudtraining/temp/stock-elk.log